apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gmaps-location-service.fullname" . }}-secret
  labels:
    {{- include "gmaps-location-service.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.googleMapsApiKey | b64enc | quote }}